# Generated by Django 4.2.5 on 2023-10-10 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('img', models.CharField(blank=True, max_length=100, null=True, verbose_name='Изображение')),
                ('bdate', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(max_length=1, verbose_name='Пол')),
                ('email', models.CharField(max_length=50, verbose_name='Эл. почта')),
                ('available_mem', models.FloatField(default=102400, verbose_name='Память на хранение')),
                ('phone', models.CharField(max_length=20, verbose_name='Тел. номер')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('login', models.CharField(max_length=20, verbose_name='Логин')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('is_moder', models.BooleanField(default=False, verbose_name='Модератор')),
            ],
        ),
        migrations.CreateModel(
            name='sending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Создано')),
                ('sent', models.DateTimeField(verbose_name='Отправлен')),
                ('received', models.DateTimeField(verbose_name='Получен')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('moder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moder_id', to='lab1.user', verbose_name='ID_Модератор')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='lab1.user', verbose_name='ID_Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='sendingReciver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reciver_count', models.IntegerField(default=0, verbose_name='Количество получателей в данном запросе')),
                ('Receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1.receiver', verbose_name='Получатель')),
                ('Sending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1.sending', verbose_name='Отправка файла')),
            ],
            options={
                'unique_together': {('Receiver', 'Sending')},
            },
        ),
    ]
