# Generated by Django 4.2.5 on 2023-10-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sendingReciver',
            new_name='sendingReceiver',
        ),
    ]
