# Generated by Django 4.2.5 on 2023-12-26 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import receivers_selection_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('login', models.CharField(max_length=32, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=256, verbose_name='Пароль')),
                ('is_moder', models.BooleanField(default=False, verbose_name='Модератор')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Админ')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Все права')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', receivers_selection_api.models.NewUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('status', models.CharField(default='1', max_length=1, verbose_name='Статус отображения')),
                ('bdate', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(max_length=1, verbose_name='Пол')),
                ('email', models.CharField(max_length=50, verbose_name='Эл. почта')),
                ('available_mem', models.FloatField(default=102400, verbose_name='Память на хранение')),
                ('phone', models.CharField(max_length=20, verbose_name='Тел. номер')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Последнее изменение')),
            ],
        ),
        migrations.CreateModel(
            name='sending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Создано')),
                ('sent', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен')),
                ('received', models.DateTimeField(blank=True, null=True, verbose_name='Получен')),
                ('status', models.CharField(default='I', max_length=20, verbose_name='Статус')),
                ('status_send', models.CharField(default='Q', max_length=20, verbose_name='Статус отправки')),
                ('moder_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moder_name', to=settings.AUTH_USER_MODEL, verbose_name='ID_Модератор')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_name', to=settings.AUTH_USER_MODEL, verbose_name='ID_Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='sendingReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_contact', models.BooleanField(default=False, verbose_name='ваш контакт?')),
                ('Reciver_count', models.IntegerField(default=0, verbose_name='Количество получателей в данном запросе')),
                ('Receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receivers_selection_api.receiver', verbose_name='Получатель')),
                ('Sending', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receivers_selection_api.sending', verbose_name='Отправка файла')),
            ],
            options={
                'unique_together': {('Receiver', 'Sending')},
            },
        ),
    ]
