# Generated by Django 4.2.5 on 2023-11-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivers_selection_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='file_extension',
            field=models.CharField(default='jpg', max_length=10, verbose_name='Расширение файла изображения'),
        ),
        migrations.AddField(
            model_name='receiver',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Последнее изменение'),
        ),
        migrations.AddField(
            model_name='user',
            name='active_request',
            field=models.IntegerField(default=-1, verbose_name='Активная заявка'),
        ),
    ]
