# Generated by Django 4.2.5 on 2024-01-13 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receivers_selection_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='moder_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moder_name', to=settings.AUTH_USER_MODEL, verbose_name='ID_Модератор'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL, verbose_name='ID_Пользователь'),
        ),
        migrations.AlterField(
            model_name='sendingreceiver',
            name='Receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receivers_selection_api.receiver', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='sendingreceiver',
            name='Sending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receivers_selection_api.sending', verbose_name='Отправка файла'),
        ),
    ]
