# Generated by Django 4.2.5 on 2024-01-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receivers_selection_api', '0002_alter_sending_moder_name_alter_sending_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
