# Generated by Django 4.2.5 on 2023-11-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivers_selection_api', '0002_receiver_file_extension_receiver_last_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiver',
            name='file_extension',
        ),
        migrations.AddField(
            model_name='sendingreceiver',
            name='is_contact',
            field=models.BooleanField(default=False, verbose_name='ваш контакт?'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='status',
            field=models.CharField(default='I', max_length=20, verbose_name='Статус'),
        ),
    ]
