# Generated by Django 4.2.5 on 2024-01-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receivers_selection_api', '0003_rename_name_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
