# Generated by Django 4.2.5 on 2024-01-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receivers_selection_api', '0004_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='username',
        ),
    ]
