# Generated by Django 4.2.5 on 2023-11-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receivers_selection_api', '0004_alter_sending_received_alter_sending_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_request',
        ),
    ]
