# Generated by Django 4.2.5 on 2023-12-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receivers_selection_api', '0005_remove_user_active_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='moder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moder_id', to='receivers_selection_api.user', verbose_name='ID_Модератор'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_id', to='receivers_selection_api.user', verbose_name='ID_Пользователь'),
        ),
        migrations.AlterField(
            model_name='sendingreceiver',
            name='Receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receivers_selection_api.receiver', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='sendingreceiver',
            name='Sending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receivers_selection_api.sending', verbose_name='Отправка файла'),
        ),
    ]
