# Generated by Django 4.2.5 on 2024-01-22 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receivers_selection_api', '0005_rename_login_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='moder_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moder_name', to=settings.AUTH_USER_MODEL, verbose_name='ID_Модератор'),
        ),
    ]
